/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semester_two;

import java.io.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author MRS SAFIYA
 */

public class Delete extends javax.swing.JFrame {

    static final String DB_URL = "jdbc:mysql://localhost:3306/semester_two";
    static final String USER = "root";
    static final String PASS = "";
    static final String QUERY = "SELECT * FROM `employee_records` WHERE Employee_Number = ?";
    static final String query_delete = "DELETE FROM `employee_records` WHERE Employee_Number = ?";
    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Employeedel = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        employee_records = new javax.swing.JTable();
        Modify = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Display = new javax.swing.JButton();
        Count = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DELETE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMPLOYEE NUMBER : ");

        Delete.setBackground(new java.awt.Color(211, 211, 211));
        Delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 87, 51));
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        employee_records.setBackground(new java.awt.Color(240, 240, 240));
        employee_records.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Number", "First Name", "Last Name", "Age", "Basic Salary", "Department", "Date of joining", "Address City", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        employee_records.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employee_recordsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employee_records);

        Modify.setBackground(new java.awt.Color(211, 211, 211));
        Modify.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Modify.setForeground(new java.awt.Color(76, 175, 80));
        Modify.setText("MODIFY");
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyActionPerformed(evt);
            }
        });

        Search.setBackground(new java.awt.Color(211, 211, 211));
        Search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Search.setForeground(new java.awt.Color(0, 0, 128));
        Search.setText("SEARCH");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Display.setBackground(new java.awt.Color(211, 211, 211));
        Display.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Display.setForeground(new java.awt.Color(0, 0, 128));
        Display.setText("DISPLAY RECORDS");
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });

        Count.setBackground(new java.awt.Color(211, 211, 211));
        Count.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Count.setForeground(new java.awt.Color(0, 0, 128));
        Count.setText("COUNT RECORDS");
        Count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(211, 211, 211));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(0, 115, 230));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Employeedel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(117, 117, 117)
                        .addComponent(Search)
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(95, 95, 95)
                        .addComponent(Display)
                        .addGap(50, 50, 50)
                        .addComponent(Count)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Employeedel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Count, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int getCountOfRecords() {
        try {
            Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM employee_records");
            
            if (rs.next()) {
                int count = rs.getInt(1);
                return count;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Handle the exception as needed
        }
         return -1; // Return -1 to indicate an error
    }
    
    // Add a method to refresh the table data
private void refreshTableData() {
    String QUER = "SELECT * FROM `employee_records`";
    try {
        Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
        PreparedStatement stmt = conn.prepareStatement(QUER);
        ResultSet rs = stmt.executeQuery();
        DefaultTableModel model = (DefaultTableModel) employee_records.getModel();
        model.setRowCount(0);
        while (rs.next()) {
            int column1Value = rs.getInt(1);
            String column2Value = rs.getString(2);
            String column3Value = rs.getString(3);
            int column4Value = rs.getInt(4);
            int column5Value = rs.getInt(5);
            String column6Value = rs.getString(6);
            String column7Value = rs.getString(7);
            String column8Value = rs.getString(8);
            String column9Value = rs.getString(9);
            
            model.addRow(new Object[]{column1Value, column2Value, column3Value, column4Value, column5Value, column6Value, column7Value, column8Value, column9Value});
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "Error: " + ex.getMessage());
    }
}


// Add this method to update the text file after deletion
private void updateTextFile() {
    try {
        String filename = "Employee Records.txt";
        FileWriter fileWriter = new FileWriter(filename);
        BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
        DefaultTableModel model = (DefaultTableModel) employee_records.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            // Format the record as a string
            String record = String.format("Employee Number : %s\nFirst Name : %s\nLast Name : %s\nAge : %s\nBasic Salary : %s\nDepartment : %s\nDate : %s\nAddress : %s\nPhone : %s\n\n",
                    model.getValueAt(i, 0),
                    model.getValueAt(i, 1),
                    model.getValueAt(i, 2),
                    model.getValueAt(i, 3),
                    model.getValueAt(i, 4),
                    model.getValueAt(i, 5),
                    model.getValueAt(i, 6),
                    model.getValueAt(i, 7),
                    model.getValueAt(i, 8)
            );

            bufferedWriter.write(record);
        }

        bufferedWriter.close();
        fileWriter.close();
    } catch (IOException e) {
        e.printStackTrace();
    }
}

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        if(Employeedel.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Field cannot be empty");
        }
        else{
            try {
        Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);

        String Empnum = Employeedel.getText();

        // Check if the employee number exists in the database
        PreparedStatement checkExistence = conn.prepareStatement(QUERY);
        checkExistence.setString(1, Empnum);
        ResultSet resultSet = checkExistence.executeQuery();

        if (!resultSet.next()) {
            JOptionPane.showMessageDialog(rootPane, "Employee Number does not exist");
        } else {
            // Employee number exists, proceed with deletion
            PreparedStatement prst = conn.prepareStatement(query_delete);
            prst.setString(1, Empnum);
            prst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Record Deleted Successfully");
            DefaultTableModel model = (DefaultTableModel) employee_records.getModel();
            int selectedRow = employee_records.getSelectedRow();
            if (selectedRow != -1) {
                model.removeRow(selectedRow);
            }

            // Refresh the table data after deletion
            refreshTableData();

            // Now, update the text file with the updated records
            updateTextFile();
        }
        conn.close();
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Search sh = new Search();
        sh.setVisible(true);
    }//GEN-LAST:event_SearchActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Display dis = new Display();
        dis.setVisible(true);
    }//GEN-LAST:event_DisplayActionPerformed

    private void CountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountActionPerformed
        // TODO add your handling code here:
        int count = getCountOfRecords();
        if (count >= 0) {
        JOptionPane.showMessageDialog(rootPane, "Total records in the database: " + count);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error retrieving record count.");
        }        
    }//GEN-LAST:event_CountActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Screensplash sp = new Screensplash();
        sp.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String QUE = "SELECT * FROM `employee_records`";
        try {
            Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
            PreparedStatement stmt = conn.prepareStatement(QUE);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel)employee_records.getModel();  
            model.setRowCount(0);
            while(rs.next()){
                int column1Value = rs.getInt(1);
                String column2Value = rs.getString(2);
                String column3Value = rs.getString(3);
                int column4Value = rs.getInt(4);
                int column5Value = rs.getInt(5);
                String column6Value = rs.getString(6);
                String column7Value = rs.getString(7);
                String column8Value = rs.getString(8);
                String column9Value = rs.getString(9);
                
                model.addRow(new Object[]{column1Value, column2Value, column3Value, column4Value, column5Value, column6Value, column7Value, column8Value, column9Value});
            }
        }
        catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane,"Error: " +ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void employee_recordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employee_recordsMouseClicked
        // TODO add your handling code here:
        // Display Selected Row In Text Fields
        int i = employee_records.getSelectedRow();
        TableModel model = employee_records.getModel();
        Employeedel.setText(model.getValueAt(i,0).toString());
    }//GEN-LAST:event_employee_recordsMouseClicked

    private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Modify up = new Modify();
        up.setVisible(true);
    }//GEN-LAST:event_ModifyActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Count;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Display;
    private javax.swing.JTextField Employeedel;
    private javax.swing.JButton Modify;
    private javax.swing.JButton Search;
    private javax.swing.JButton back;
    private static javax.swing.JTable employee_records;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
