/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semester_two;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

import static semester_two.Search.DB_URL;

/**
 *
 * @author MRS SAFIYA
 */
public class Search extends javax.swing.JFrame {

    static final String DB_URL = "jdbc:mysql://localhost:3306/semester_two";
    static final String USER = "root";
    static final String PASS = "";
    static final String QUERY = "SELECT * FROM `employee_records` WHERE Employee_Number = ?";
    
    /**
     * Creates new form Search
     */
    
    DefaultTableModel model;
    public Search() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        Department = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        modify = new javax.swing.JButton();
        Display_records = new javax.swing.JButton();
        Count_Records = new javax.swing.JButton();
        EmployeeNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        employee_records = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEARCH", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Number :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name : ");

        FirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FirstNameKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name : ");

        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(0, 115, 230));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Department : ");

        LastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LastNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LastNameKeyReleased(evt);
            }
        });

        Department.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Department.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DepartmentKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DepartmentKeyReleased(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        modify.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        modify.setForeground(new java.awt.Color(76, 175, 80));
        modify.setText("MODIFY");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        Display_records.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Display_records.setForeground(new java.awt.Color(0, 0, 128));
        Display_records.setText("DISPLAY RECORDS");
        Display_records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Display_recordsActionPerformed(evt);
            }
        });

        Count_Records.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Count_Records.setForeground(new java.awt.Color(0, 0, 128));
        Count_Records.setText("COUNT RECORDS");
        Count_Records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Count_RecordsActionPerformed(evt);
            }
        });

        EmployeeNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmployeeNumberKeyReleased(evt);
            }
        });

        employee_records.setBackground(new java.awt.Color(240, 240, 240));
        employee_records.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Number", "First Name", "Last Name", "Age", "Basic Salary", "Department", "Date of joining", "Address City", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employee_records);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)
                                .addComponent(modify)
                                .addGap(0, 120, Short.MAX_VALUE)))
                        .addGap(53, 53, 53)
                        .addComponent(Display_records)
                        .addGap(100, 100, 100)
                        .addComponent(Count_Records))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Department, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(LastName)))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modify, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Display_records, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Count_Records, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void search_EmployeeNumber(String str){
        model = (DefaultTableModel) employee_records.getModel();
        TableRowSorter<TableModel> epn = new TableRowSorter<>(model);
        employee_records.setRowSorter(epn);
    
    // Assuming that the Employee Number column is of Integer type,
    // you can specify the column class for proper filtering.
    epn.setRowFilter(RowFilter.regexFilter(str, 0));
    }
    
    public void search_FirstName(String str){
        model = (DefaultTableModel) employee_records.getModel();
        TableRowSorter<TableModel> fn = new TableRowSorter<>(model);
        employee_records.setRowSorter(fn);
    
    // Assuming that the Employee Number column is of Integer type,
    // you can specify the column class for proper filtering.
    fn.setRowFilter(RowFilter.regexFilter("(?i)^" + Pattern.quote(str), 1));
    }
    
    public void search_LastName(String str){
        model = (DefaultTableModel) employee_records.getModel();
        TableRowSorter<TableModel> fn = new TableRowSorter<>(model);
        employee_records.setRowSorter(fn);
    
    // Assuming that the Employee Number column is of Integer type,
    // you can specify the column class for proper filtering.
    fn.setRowFilter(RowFilter.regexFilter("(?i)^" + Pattern.quote(str), 2));
    }

    public void search_Department(String str){
        model = (DefaultTableModel) employee_records.getModel();
        TableRowSorter<TableModel> fn = new TableRowSorter<>(model);
        employee_records.setRowSorter(fn);
    
    // Assuming that the Employee Number column is of Integer type,
    // you can specify the column class for proper filtering.
    fn.setRowFilter(RowFilter.regexFilter("(?i)^" + Pattern.quote(str), 5));
    }
    private int getCountOfRecords() {
        try {
            Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM employee_records");
            
            if (rs.next()) {
                int count = rs.getInt(1);
                return count;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Error: " +ex.getMessage());
            // Handle the exception as needed
        }
         return -1; // Return -1 to indicate an error
    }
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Screensplash sp = new Screensplash();
        sp.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Delete del = new Delete();
        del.setVisible(true);
    }//GEN-LAST:event_DeleteActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Modify up = new Modify();
        up.setVisible(true);
    }//GEN-LAST:event_modifyActionPerformed

    private void Display_recordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Display_recordsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Display dis = new Display();
        dis.setVisible(true);
    }//GEN-LAST:event_Display_recordsActionPerformed

    private void Count_RecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Count_RecordsActionPerformed
        // TODO add your handling code here:
        int count = getCountOfRecords();
        if (count >= 0) {
        JOptionPane.showMessageDialog(rootPane, "Total records in the database: " + count);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error retrieving record count.");
        }
    }//GEN-LAST:event_Count_RecordsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String QUE = "SELECT * FROM `employee_records`";
        try {
            Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
            PreparedStatement stmt = conn.prepareStatement(QUE);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel)employee_records.getModel();  
            model.setRowCount(0);
            while(rs.next()){
                int column1Value = rs.getInt(1);
                String column2Value = rs.getString(2);
                String column3Value = rs.getString(3);
                int column4Value = rs.getInt(4);
                int column5Value = rs.getInt(5);
                String column6Value = rs.getString(6);
                String column7Value = rs.getString(7);
                String column8Value = rs.getString(8);
                String column9Value = rs.getString(9);
                
                model.addRow(new Object[]{column1Value, column2Value, column3Value, column4Value, column5Value, column6Value, column7Value, column8Value, column9Value});
            }
        }
        catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane,"Error: " +ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void EmployeeNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmployeeNumberKeyReleased
        // TODO add your handling code here:
        String searchString = EmployeeNumber.getText();
        search_EmployeeNumber(searchString);
    }//GEN-LAST:event_EmployeeNumberKeyReleased

    private void FirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNameKeyReleased
        // TODO add your handling code here:
        String searchString = FirstName.getText();
        search_FirstName(searchString);
    }//GEN-LAST:event_FirstNameKeyReleased

    private void LastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameKeyPressed

    }//GEN-LAST:event_LastNameKeyPressed

    private void DepartmentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DepartmentKeyPressed

    }//GEN-LAST:event_DepartmentKeyPressed

    private void LastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameKeyReleased
        // TODO add your handling code here:
        String searchString = LastName.getText();
        search_LastName(searchString);
    }//GEN-LAST:event_LastNameKeyReleased

    private void DepartmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DepartmentKeyReleased
        // TODO add your handling code here:
        String searchString = Department.getText();
        search_Department(searchString);
    }//GEN-LAST:event_DepartmentKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Count_Records;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Department;
    private javax.swing.JButton Display_records;
    private javax.swing.JTextField EmployeeNumber;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JButton back;
    private static javax.swing.JTable employee_records;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modify;
    // End of variables declaration//GEN-END:variables
}
